apiVersion: v1
kind: Service
metadata:
  name: lab-nginx
  namespace: lab-argocd
  labels:
    app: lab-nginx
spec:
  selector:
    app: lab-nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
